name: docker image push
on: 
   push:
     branches:  [master]
   pull_request:
     branches:  [master]
jobs:
   builds:
       runs-on: ubuntu-latest
       steps:
       - name: Build and push Docker images
         uses: docker/build-push-action@v1
         run : |
           echo "${{ secrets.DOCKER_PASSWORD }}"  | docker login -u "tinku13" --password-stdin
           docker image built -t  tinku13/ci-cd-test
           docker push tinku13/os-img
